name: lint
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Pick golang_info
        id: go
        run: echo ::set-output name=version::$(grep golang .tool-versions | awk '{print $2}')

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.go.outputs.version }}
      - run: make lint
